services:
  adminer:
    container_name: adminer

    image: adminer

    restart: unless-stopped

    networks:
      - ${EXTERNAL_NETWORK}

    environment:
      ADMINER_DESIGN: ng9

    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"

    command: ["php", "-d", "post_max_size=500M", "-d", "upload_max_filesize=500M", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]

networks:
  external-service-network:
    external: true
