version: "3.8"

services:
  mongo:
    container_name: service_mongodb
    image: mongo

  mysql:
    container_name: service_mysql
    image: mysql:8

  postgresql:
    container_name: service_pg
    image: postgres:14-alpine

  adminer:
    image: adminer
    container_name: service_pg_admin

  redis:
    container_name: service_redis
    image: redis:6-alpine3.15

networks:
  campus_network:
