version: "3.9"

services:
  elastic:
    container_name: service_elastic
    image: elasticsearch:7.17.3
    restart: unless-stopped
    networks:
      - service-external-network
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - ./volumes/elasticsearch:/usr/share/elasticsearch/data

networks:
  service-external-network:
    external: true
