version: "3.8"

services:
  elastic:
    container_name: service_elastic
    image: elasticsearch:7.16.3
    restart: always
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
    volumes:
      - elastic_store:/usr/share/elasticsearch/data

volumes:
  elastic_store:
