version: "3.9"

services:
  elasticsearch:
    container_name: elasticsearch

    image: elasticsearch:7.17.6

    restart: unless-stopped

    networks:
      - ${EXTERNAL_NETWORK}

    environment:
      - "discovery.type=single-node"

    ports:
      - "${ELASTICSEARCH_PORT}:${ELASTICSEARCH_PORT}"

    volumes:
      - "./volumes/elasticsearch:/usr/share/elasticsearch/data"

    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail elasticsearch:${ELASTICSEARCH_PORT}/_cluster/health || exit 1"]
      interval: 20s
      timeout: 30s
      retries: 3

networks:
  external-service-network:
    external: true
