version: "3.8"

services:
  mongo:
    container_name: service_mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_store:/data/db

volumes:
  mongodb_store:
