version: "3.9"

services:
  mongo:
    container_name: service_mongodb
    image: mongo:latest
    restart: unless-stopped
    networks:
      - service-external-network
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongodb:/data/db

networks:
  service-external-network:
    external: true
