services:
  mongodb:
    container_name: mongodb

    image: mongo:latest

    restart: unless-stopped

    networks:
      - ${EXTERNAL_NETWORK}

    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

    volumes:
      - ./volumes/mongodb:/data/db

networks:
  external-service-network:
    external: true

