version: "3.8"

services:
  mongo:
    container_name: service_mongodb
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=helloworld
    ports:
      - 27017:27017
    volumes:
      - mongodb_store:/data/db

volumes:
  mongodb_store:
