version: "3.9"

services:
  mysql:
    container_name: service_mysql
    image: mysql:8
    restart: unless-stopped
    command: --authentication_policy=mysql_native_password
    networks:
      - service-external-network
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: helloworld

networks:
  service-external-network:
    external: true
