version: "3.9"

services:
  mysql:
    container_name: mysql

    image: mysql:8

    restart: unless-stopped

    command: --authentication_policy=mysql_native_password

    networks:
      - ${EXTERNAL_NETWORK}

    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"

    volumes:
      - "./volumes/mysql:/var/lib/mysql"

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 15s
      timeout: 20s
      retries: 10

networks:
  external-service-network:
    external: true
