version: "3.8"

services:
  mysql:
    container_name: service_mysql
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql_store:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    networks:
      - campus_network

volumes:
  mysql_store:

networks:
  campus_network:
