version: "3.9"

services:
  postgresql:
    container_name: service_pg
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - service-external-network
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    container_name: service_adminer
    image: adminer
    restart: always
    networks:
      - service-external-network
    ports:
      - 8080:8080

networks:
  service-external-network:
    external: true
