version: "3.9"

services:
  portainer:
    container_name: service_portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    networks:
      - service-external-network
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data

networks:
  service-external-network:
    external: true
