services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:alpine
    restart: unless-stopped
    networks:
      - ${EXTERNAL_NETWORK}
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

    volumes:
      - ./volumes/rabbitmq:/var/lib/rabbitmq

networks:
  external-service-network:
    external: true
