version: "3.9"

services:
  redis:
    container_name: redis

    image: redis:7.0.0-alpine3.15

    restart: unless-stopped

    networks:
      - ${EXTERNAL_NETWORK}

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - "./volumes/redis:/data"

networks:
  external-service-network:
    external: true
