version: "3.9"

services:
  redis:
    container_name: service_redis
    image: redis:7.0.0-alpine3.15
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_store:/data

volumes:
  redis_store:
