version: "3.9"

services:
  redis:
    container_name: service_redis
    image: redis:7.0.0-alpine3.15
    restart: unless-stopped
    networks:
      - service-external-network
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data

networks:
  service-external-network:
    external: true
